### PR TITLE
Add dkms support

### PR DESCRIPTION
**Pull request by parkerlreed**
Posting as is so we can work it out. I'll need a refresher on how to squash the new commits down to one at the end ;D

I will take a look at that Kbuild section in the documents

### CODE REVIEW

**Comment by berarma** [comment]
What do you think about leaving the Makefile as is (not that I mind changing it) and changing the install instructions in the README instead?

**Comment by parkerlreed** [comment]
Problem is, dkms passes in the KERNELRELEASE to make. So it may at least need the breakout in Kbuild for the first section. I'll give that a test

**Comment by parkerlreed** [comment]
Working on rebasing this and fixing my fucked up commit text (cmake.... derp)

**Comment by parkerlreed** [comment]
I've screwed this all up. I'll just recreate and push anew (with note in readme)

**Pull request closed without merging**
