### PR TITLE
Rebase code to Linux kernel 6.3

### PR DESCRIPTION
**Pull request by motolav**
This code is untested but includes patches that are missing from the original forked code that are in the kernel

Kernel commits that were missing from the repo are [1](https://github.com/torvalds/linux/commit/93020953d0fa7035fd036ad87a47ae2b7aa4ae33), [2](https://github.com/torvalds/linux/commit/d9d4b1e46d9543a82c23f6df03f4ad697dab361b), [3](https://github.com/torvalds/linux/commit/d180b6496143cd360c5d5f58ae4b9a8229c1f344)

I will mark ready for review after I test it

### CODE REVIEW

**Comment by berarma** [comment]
I'll review it as soon as I can. Thanks.

**Comment by motolav** [comment]
Kernel 6.3 includes the ID ```#define USB_DEVICE_ID_LOGITECH_G923_XBOX_WHEEL	0xc26e``` with this [commit ](https://git.kernel.org/pub/scm/linux/kernel/git/hid/hid.git/commit/drivers/hid?h=for-linus-2023022201&id=e8ab7a10edc7d071f64d8a8352b88e7d7477854a) so once all the 6.3 HID changes are merged I'll update the PR.

**Comment by motolav** [comment]
This PR is complete now and I fixed the README so it says the G923 XBOX will have FFB support in kernel 6.3.

**Comment by jashton-vayu** [comment]
@motolav are there any updates on this? I would like to use it with my G923. I did try building & installing your fork but did not seem to pick up the device for me on Ubuntu 20.04

**Comment by berarma** [comment]
> @motolav are there any updates on this? I would like to use it with my G923. I did try building & installing your fork but did not seem to pick up the device for me on Ubuntu 20.04

Is it the XBox version? This driver is only for the PS version.

**Comment by jashton-vayu** [comment]
@berarma If I'm not mistaken, Kernel 6.3 includes support for Xbox G923, I thought that's what this rebase was providing https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.3

**Comment by berarma** [comment]
> @berarma If I'm not mistaken, Kernel 6.3 includes support for Xbox G923, I thought that's what this rebase was providing https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.3 

No, this isn't related.

**Comment by motolav** [comment]
@jashton-vayu  The Xbox G923 wheel uses a different driver that doesn't involve any of this code and doesn't need any of the improvements that this driver has IIRC.

> This module is not compatible with the Logitech G920 Driving Force and XBOX/PC
version of the Logitech G923 (046d:c26d, 046d:c26e). Both wheels use the HID++
protocol and are supported by the HID++ driver as of kernel 6.3.

**Comment by jashton-vayu** [comment]
@motolav Is it possible to back-port the changes from 6.3 in a similar way to this PR?

**Comment by motolav** [comment]
@jashton-vayu you don't understand, you don't need this driver at all. As long as your distro is using kernel 6.3 you can use your wheel on Linux now without any modification.

**Comment by berarma** [comment]
@molotav, thanks for your work on this. I'm ashamed it took me so long to merge it.

**Pull request merged**
