### PR TITLE
dkms: remove REMAKE_INITRD

### PR DESCRIPTION
**Pull request by Arsconyl**
By selecting this option, dkms attempts to add the module into the user
init ramdisk. While it seems like a cool idea it is not something the
module should decide by the user or distribution on their behalf.

### CODE REVIEW

**Comment by berarma** [comment]
Without this line most people will keep using the default kernel module without knowing it. They would need to remove the default module and load this one manually after each reboot. What do you suggest to avoid this situation that users will complain about?

**Comment by parkerlreed** [comment]
REMAKE_INITRD has been deprecated. I'm not sure what has to be done otherwise but all modules throw this warning on build now (At least on Arch)

**Comment by berarma** [comment]
We'll have to tell the user to update the `initrd` manually. AFAIK there's not unique method to update the `initrd` across distributions but I think there's currently only two commands to do it, `initramfs` and `dracut`. Correct me if I'm wrong.

Could you add instructions to the README considering most users don't know what an `initrd` is?

**Comment by parkerlreed** [comment]
From what I've seen the system still regenerates initramfs at least when updating the kernel on Arch. It just skips doing it on every DKMS install as that becomes redundant. 

As for installing this on other distributions, I'm not sure exactly what would be needed for those.

**Comment by berarma** [comment]
Yes, it will, but only when the kernel is reinstalled, updated or the initrd is manually regenerated. It doesn't make much sense that it's added to the initrd just after updating the kernel but not when installing the module.

**Comment by berarma** [comment]
I've merged but I still have to add instructions to the README or most users won't know what to do when the driver doesn't load after a reboot.

**Pull request merged**
