### PR TITLE
Update with Kbuild split and dkms.conf

### PR DESCRIPTION
**Pull request by parkerlreed**

### CODE REVIEW

**Comment by berarma** [comment]
I've renamed the DKMS module and changed the destination directory so that it replaces the original module. I think this is what users expect from DKMS installed modules.

I've adjusted the instructions in the README and added the `clean` target so DKMS doesn't throw errors.

I did it myself because I've used DKMS as a user but hadn't ever done a DKMS package myself and I had to check how it worked before asking any changes. At this point I think it will be easier commiting my changes than changing this PR and merging. I'll keep you as the author of the commit for your contribution if you don't mind.

**Comment by parkerlreed** [comment]
Sweet! Yeah no problem.

**Comment by berarma** [comment]
Commit 3dfe622b850987a4b39919095ec40bdbf5ab6d59

**Comment by parkerlreed** [comment]
Oh sweet so that's just overwriting the existing module?

**Comment by parkerlreed** [comment]
Ahh very cool

```
Running module version sanity check.
 - Original module
   - Found /usr/lib/modules/5.3.13-arch1-1/kernel/drivers/hid/hid-logitech.ko.xz
   - Storing in /var/lib/dkms/new-lg4ff/original_module/5.3.13-arch1-1/x86_64/
   - Archiving for uninstallation purposes
 - Installation
   - Installing to /usr/lib/modules/5.3.13-arch1-1/kernel/drivers/hid/

depmod.....

```

**Pull request closed without merging**
